# Generated by Django 4.1.13 on 2023-11-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
    ]
